[project]
name = "livetrivia"
version = "0.1.0"
description = "Game server for live trivia (bearcat game), a real-time multiplayer trivia game."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.3",
    "genanki>=0.13.1",
    "lazy-loader>=0.4",
    "python-dotenv>=1.2.1",
    "sqlmodel>=0.0.27",
]

[project.optional-dependencies]
backend = [
    "fastapi>=0.121.1",
    "gunicorn>=23.0.0",
    "sqlalchemy[asyncio]>=2.0.44",
    "pypdf>=6.2.0",
    "youtube-transcript-api>=1.2.3",
    "python-multipart>=0.0.21",
    "aiosqlite>=0.22.1",
    "bcrypt>=5.0.0",
    "pydantic[email]>=2.12.4",
    "pyjwt>=2.10.1",
    "aioboto3>=15.5.0",
    "types-aioboto3[essential]>=15.5.0",
    "python-docx>=1.2.0",
    "genanki>=0.13.1",
]
frontend = [
    "dash-ag-grid>=32.3.2",
    "dash-iconify>=0.1.2",
    "dash-mantine-components>=2.4.0",
    "dash[async]>=3.3.0",
    "gunicorn>=23.0.0",
]
dev = [
    "ruff>=0.14.5",
    "pytest>=9.0.2",
    "pandas>=3.0.0",
    "livetrivia[backend,frontend]",
    "uvicorn>=0.38.0",
]
sglang = [
    "sglang>=0.5.2",
]

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[tool.uv.pip]
all-extras = true

[tool.ruff.lint.isort]
known-first-party = ["livetrivia"]
